trigger:
  branches:
    include:
      - main
  
  paths:
    include:
      - host/**
      - remotes/**

pool:
  name: LocalPool

variables:
  storageAccountName: $(AZURE_STORAGE_ACCOUNT_NAME)  
  buildFolder: build

stages:
  - stage: DetectChanges
    displayName: 'Detect MFE Changes'
    jobs:
      - job: DetectChanges
        displayName: 'Detect which MFEs have changed'
        steps:
          - checkout: self
            fetchDepth: 0
        
          - powershell: |
              $configPath = "mfe.config.json"

              if (!(Test-Path $configPath)) {
                Write-Error "mfe.config.json not found"
                exit 1
              }
              
              $mfeMap = Get-Content $configPath | ConvertFrom-Json

              if ("$(Build.Reason)" -eq "PullRequest") {
                $changedFiles = git diff --name-only origin/main...HEAD
              }
              else {
                $changedFiles = git diff --name-only HEAD~1 HEAD
              }

              Write-Host "Changed files:"
              $changedFiles | ForEach-Object { Write-Host $_ }

              $matrix = @{}

              foreach ($mfe in $mfeMap.Keys) {
                $path = $mfeMap[$mfe]

                if ($changedFiles -match "^$path/") {
                  $matrix[$mfe] = @{
                    mfeName   = $mfe
                    mfePath   = $path
                    deployPath = $path
                  }
                }                
              }

              if ($matrix.Count -eq 0) {
                Write-Host "No changes detected in any MFE. Exiting pipeline."
                exit 0
              }
              
              $json = $matrix | ConvertTo-Json -Compress
              Write-Host "##vso[task.setvariable variable=mfeMatrix;isOutput=true]$json"
            name: detectChanges

  - stage: BuildAndDeploy
    displayName: 'Build and Deploy Changed MFEs'
    dependsOn: DetectChanges
    variables:
      mfeMatrix: $[ stageDependencies.DetectChanges.Detect.outputs['detect.mfeMatrix'] ]

    jobs:
      - job: BuildDeploy
        displayName: 'Build and Deploy Changed MFEs'
        condition: ne(variables.mfeMatrix, '{}')
        strategy:
          matrix: $[ fromJson(variables.mfeMatrix) ]
        steps:
          - template: .azure/winAgent/build-deploy-template.yml
            parameters:
              mfeName: $(matrix.mfeName)
              mfePath: $(matrix.mfePath)
              deployPath: $(matrix.deployPath)
              storageAccountName: $(storageAccountName)
              buildFolder: $(buildFolder)
      