trigger:
  branches:
    include:
      - main
  
  paths:
    include:
      - host/**
      - remotes/**

pool:
  name: LocalPool

variables:
  storageAccountName: $(AZURE_STORAGE_ACCOUNT_NAME)  
  buildFolder: build

stages:
  - stage: DetectChanges
    displayName: 'Detect MFE Changes'
    jobs:
      - job: DetectChanges
        displayName: 'Detect which MFEs have changed'
        steps:
          - checkout: self
            fetchDepth: 0
        
          - powershell: |
              Write-Host "Detecting changes between commits..."

              if ("$(Build.Reason)" -eq "PullRequest") {
                $changedFiles = git diff --name-only origin/main...HEAD
              }
              else {
                $changedFiles = git diff --name-only HEAD~1 HEAD
              }

              Write-Host "Changed files:"
              Write-Host $changedFiles

              $HOST_CHANGED = $false
              $HOME_CHANGED = $false
              $LISTMOVIES_CHANGED = $false
              $VIEWMOVIE_CHANGED = $false

              if ($changedFiles -match '^host/') {
                $HOST_CHANGED = $true
              }

              if ($changedFiles -match '^remotes/home/') {
                $HOME_CHANGED = $true
              }

              if ($changedFiles -match '^remotes/list-movies/') {
                $LISTMOVIES_CHANGED = $true
              }

              if ($changedFiles -match '^remotes/view-movie/') {
                $VIEWMOVIE_CHANGED = $true
              }

              Write-Host "##vso[task.setvariable variable=hostChanged;isOutput=true]$HOST_CHANGED"
              Write-Host "##vso[task.setvariable variable=homeChanged;isOutput=true]$HOME_CHANGED"
              Write-Host "##vso[task.setvariable variable=listmoviesChanged;isOutput=true]$LISTMOVIES_CHANGED"
              Write-Host "##vso[task.setvariable variable=viewmovieChanged;isOutput=true]$VIEWMOVIE_CHANGED"

              Write-Host "Detection results:"
              Write-Host "hostChanged: $HOST_CHANGED"
              Write-Host "homeChanged: $HOME_CHANGED"
              Write-Host "listmoviesChanged: $LISTMOVIES_CHANGED"
              Write-Host "viewmovieChanged: $VIEWMOVIE_CHANGED"
            name: detectChanges
            displayName: 'Detect Changes in MFEs'

  - stage: BuildAndDeploy
    displayName: 'Build and Deploy Changed MFEs'
    dependsOn: DetectChanges
    variables:
      hostChanged: $[ stageDependencies.DetectChanges.DetectChanges.outputs['detectChanges.hostChanged'] ]
      homeChanged: $[ stageDependencies.DetectChanges.DetectChanges.outputs['detectChanges.homeChanged'] ]
      listmoviesChanged: $[ stageDependencies.DetectChanges.DetectChanges.outputs['detectChanges.listmoviesChanged'] ]
      viewmovieChanged: $[ stageDependencies.DetectChanges.DetectChanges.outputs['detectChanges.viewmovieChanged'] ]

    jobs:
      - job: BuildDeployHost
        displayName: 'Build and Deploy Host'
        condition: eq(variables.hostChanged, 'true')
        steps:
          - template: build-deploy-template.yml
            parameters:
              mfeName: 'host'
              mfePath: 'host'
              deployPath: 'host'
              storageAccountName: $(storageAccountName)

      - job: BuildDeployHome
        displayName: 'Build and Deploy Home'
        condition: eq(variables.homeChanged, 'true')
        steps:
          - template: build-deploy-template.yml
            parameters:
              mfeName: 'home'
              mfePath: 'remotes/home'
              deployPath: 'remotes/home'
              storageAccountName: $(storageAccountName)

      - job: BuildDeployListMovies
        displayName: 'Build and Deploy ListMovies'
        condition: eq(variables.listmoviesChanged, 'true')
        steps:
          - template: build-deploy-template.yml
            parameters:
              mfeName: 'list-movies'
              mfePath: 'remotes/list-movies'
              deployPath: 'remotes/list-movies'
              storageAccountName: $(storageAccountName)

      - job: BuildDeployViewMovie
        displayName: 'Build and Deploy ViewMovie'
        condition: eq(variables.viewmovieChanged, 'true')
        steps:
          - template: build-deploy-template.yml
            parameters:
              mfeName: 'view-movie'
              mfePath: 'remotes/view-movie'
              deployPath: 'remotes/view-movie'
              storageAccountName: $(storageAccountName)