trigger:
  branches:
    include:
      - main
  
  paths:
    include:
      - host/**
      - remotes/**

pool:
  name: LocalPool

variables:
  storageAccountName: $(AZURE_STORAGE_ACCOUNT_NAME)  
  buildFolder: build

stages:
  - stage: DetectChanges
    displayName: 'Detect MFE Changes'
    jobs:
      - job: DetectChanges
        displayName: 'Detect which MFEs have changed'
        steps:
          - checkout: self
            fetchDepth: 0
        
          - task: PowerShell@2
            name: detectChanges
            displayName: Detect which MFEs have changed
            inputs:
              targetType: filePath
              filePath: .azure/scripts/detect-mfe-changes.ps1
              arguments: >
                -BuildReason "$(Build.Reason)"
                -SourcesDirectory "$(Build.SourcesDirectory)"
              pwsh: false

  - stage: BuildAndDeploy
    displayName: 'Build and Deploy Changed MFEs'
    dependsOn: DetectChanges
    variables:
      mfeMatrix: $[ stageDependencies.DetectChanges.Detect.outputs['detect.mfeMatrix'] ]

    jobs:
      - job: BuildDeploy
        displayName: 'Build and Deploy Changed MFEs'
        condition: ne(variables.mfeMatrix, '{}')
        strategy:
          matrix: $[ fromJson(variables.mfeMatrix) ]
        steps:
          - template: build-deploy-template.yml
            parameters:
              mfeName: $(matrix.mfeName)
              mfePath: $(matrix.mfePath)
              deployPath: $(matrix.deployPath)
              storageAccountName: $(storageAccountName)
              buildFolder: $(buildFolder)
      