trigger:
  branches:
    include:
      - main
  paths:
    include:
      - host/**
      - remotes/**

pool:
  name: LocalPool

variables:
  storageAccountName: mfestaticsite
  buildFolder: dist

stages:
- stage: Detect
  displayName: 'Detect Changed MFEs'
  jobs:
  - job: DetectChanges
    displayName: 'Detect which MFEs have changed'
    steps:
    - checkout: self
      fetchDepth: 0

    - task: PowerShell@2
      name: detectChanges
      displayName: Run detection script
      inputs:
        targetType: filePath
        filePath: react-mfe/.azure/winAgent/detect-mfe-changes.ps1
        arguments: >
          -BuildReason "$(Build.Reason)"
          -SourcesDirectory "$(Build.SourcesDirectory)"
        pwsh: false

    - task: PowerShell@2
      displayName: Debug Matrix
      inputs:
        targetType: inline
        pwsh: false
        script: |
          Write-Host "Matrix from script:"
          Write-Host "$(detectChanges.mfeMatrix)"

- stage: BuildAndDeploy
  displayName: 'Build and Deploy Changed MFEs'
  dependsOn: Detect
  condition: succeeded()
  jobs:
  - job: BuildAndDeploy
    displayName: 'Build and Deploy Changed MFEs (parallel)'
    strategy:
      matrix: $[ stageDependencies.Detect.DetectChanges.outputs['detectChanges.mfeMatrix'] ]
   
    steps:
    - checkout: self

    - template: build-deploy-template.yml
      parameters:
        mfeName: $(mfeName)
        mfePath: $(mfePath)
        deployPath: $(deployPath)
        storageAccountName: $(storageAccountName)
        buildFolder: $(buildFolder)