trigger: none

pool:
  name: LocalPool

variables:
  storageAccountName: $(AZURE_STORAGE_ACCOUNT_NAME)
  buildFolder: dist

stages:
- stage: FullDeploy
  displayName: 'Full Deploy All MFEs'
  jobs:
  - job: FullDeploy
    displayName: 'Build and Deploy All MFEs'
    steps:
    - checkout: self
      fetchDepth: 0

    - task: PowerShell@2
      name: readConfig
      displayName: Read mfe.config.json
      inputs:
        targetType: inline
        pwsh: false
        script: |
          $configPath = "$(Build.SourcesDirectory)\.azure\mfe.config.json"

          if (!(Test-Path $configPath)) {
            Write-Error "mfe.config.json not found"
            exit 1
          }

          $mfeMap = Get-Content $configPath | ConvertFrom-Json

          $matrix = @{}

          foreach ($mfe in $mfeMap.PSObject.Properties) {
            $matrix[$mfe.Name] = @{
              mfeName    = $mfe.Name
              mfePath    = $mfe.Value
              deployPath = $mfe.Value
            }
          }

          $json = $matrix | ConvertTo-Json -Compress
          Write-Host "##vso[task.setvariable variable=mfeMatrix;isOutput=true]$json"

    - task: PowerShell@2
      displayName: Debug matrix
      inputs:
        targetType: inline
        pwsh: false
        script: |
          Write-Host "Matrix:"
          Write-Host "$(readConfig.mfeMatrix)"

- stage: BuildAndDeploy
  displayName: 'Build and Deploy'
  dependsOn: FullDeploy

  jobs:
  - job: BuildDeploy
    displayName: 'Deploy All MFEs'
    strategy:
      matrix: $[ stageDependencies.FullDeploy.FullDeploy.outputs['readConfig.mfeMatrix'] ]

    steps:
    - template: build-deploy-template.yml
      parameters:
        mfeName: $(matrix.mfeName)
        mfePath: $(matrix.mfePath)
        deployPath: $(matrix.deployPath)
        storageAccountName: $(storageAccountName)
        buildFolder: $(buildFolder)
