trigger: none

pool:
  name: LocalPool

variables:
  storageAccountName: mfestaticsite
  buildFolder: dist

stages:
- stage: Detect
  displayName: 'Read MFE config'
  jobs:
  - job: ReadConfig
    displayName: 'Read mfe.config.json'
    steps:
    - checkout: self
      fetchDepth: 0

    - task: PowerShell@2
      name: readConfig
      displayName: Read mfe.config.json
      inputs:
        targetType: inline
        pwsh: false
        script: |
          $configPath = "$(Build.SourcesDirectory)\.azure\mfe.config.json"

          if (!(Test-Path $configPath)) {
            Write-Error "mfe.config.json not found"
            exit 1
          }

          $mfeMap = Get-Content $configPath | ConvertFrom-Json

          $matrix = @{}

          foreach ($mfe in $mfeMap.PSObject.Properties) {
            $matrix[$mfe.Name] = @{
              mfeName    = $mfe.Name
              mfePath    = $mfe.Value
              deployPath = $mfe.Value
            }
          }

          $json = $matrix | ConvertTo-Json -Depth 10 -Compress
          Write-Host "Matrix JSON:"
          Write-Host $json
          Write-Host "##vso[task.setvariable variable=mfeMatrix;isOutput=true]$json"

    - task: PowerShell@2
      displayName: Debug matrix
      inputs:
        targetType: inline
        pwsh: false
        script: |
          Write-Host "Matrix:"
          Write-Host '$(readConfig.mfeMatrix)'

- stage: BuildAndDeploy
  displayName: 'Build and Deploy MFEs (parallel)'
  dependsOn: Detect
  condition: succeeded()

  jobs:
  - job: BuildDeploy
    displayName: 'Build & Deploy MFEs'
    strategy:
      matrix: $[ stageDependencies.Detect.ReadConfig.outputs['readConfig.mfeMatrix'] ]

    steps:
    - checkout: self

    - template: build-deploy-template.yml
      parameters:
        mfeName: $(mfeName)
        mfePath: $(mfePath)
        deployPath: $(deployPath)
        storageAccountName: $(storageAccountName)
        buildFolder: $(buildFolder)
