trigger:
  branches:
    include:
      - main
  paths:
    include:
      - host/**
      - remotes/**

pool:
  name: LocalPool

variables:
  storageAccountName: mfestaticsite
  buildFolder: dist

stages:
- stage: BuildAndDeploy
  displayName: 'Detect, Build and Deploy Changed MFEs'
  jobs:
  - job: BuildDeploy
    displayName: 'Build and Deploy Changed MFEs'
    steps:
    - checkout: self
      fetchDepth: 0

    - task: PowerShell@2
      name: detectChanges
      displayName: Detect which MFEs have changed
      inputs:
        targetType: filePath
        filePath: ../.azure/winAgent/detect-mfe-changes.ps1
        arguments: >
          -BuildReason "$(Build.Reason)"
          -SourcesDirectory "$(Build.SourcesDirectory)"
        pwsh: false

    - task: PowerShell@2
      displayName: Build & Deploy each MFE
      inputs:
        targetType: inline
        pwsh: false
        script: |
          $matrixJson = '$(detectChanges.mfeMatrix)'

          if (-not $matrixJson) {
            Write-Host "No MFEs to process."
            exit 0
          }

          Write-Host "Matrix JSON:"
          Write-Host $matrixJson

          $mfeMatrix = $matrixJson | ConvertFrom-Json

          foreach ($mfe in $mfeMatrix.PSObject.Properties) {
            $name = $mfe.Value.mfeName
            $path = $mfe.Value.mfePath
            $deploy = $mfe.Value.deployPath
            
            Write-Host "Processing MFE: $name"
            Write-Host "Path: $path"

            Write-Host "##vso[task.setvariable variable=CurrentMfeName]$name"
            Write-Host "##vso[task.setvariable variable=CurrentMfePath]$path"
            Write-Host "##vso[task.setvariable variable=CurrentDeployPath]$deploy"

            Write-Host "##vso[task.setvariable variable=RunTemplate]true"

            Write-Host "Running build-deploy-template.yml for $name"
          }
    
    - template: build-deploy-template.yml
      parameters:
        mfeName: $(CurrentMfeName)
        mfePath: $(CurrentMfePath)
        deployPath: $(CurrentDeployPath)
        storageAccountName: $(storageAccountName)
        buildFolder: $(buildFolder)
